# -*- coding: utf-8 -*-
"""17.1 TIY.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pgunw04VK_StLqE1O_1kRK18z-SjRxEj
"""

import requests
import pygal
from pygal.style import LightColorizedStyle as LCS, LightenStyle as LS

def get_top_repos(language):
    """Get the top repositories on GitHub for a given language."""
    url = f"https://api.github.com/search/repositories?q=language:{language}&sort=stars"
    response = requests.get(url)
    response_dict = response.json()
    return response_dict['items']

def create_chart(repos, language):
    """Create a chart of the top repositories for a given language."""
    names, stars = [], []
    for repo in repos:
        names.append(repo['name'])
        stars.append(repo['stargazers_count'])

    my_style = LS('#333366', base_style=LCS)

    chart = pygal.Bar(style=my_style, x_label_rotation=45, show_legend=False)
    chart.title = f'Most-Starred {language.title()} Projects on GitHub'
    chart.x_labels = names

    chart.add('', stars)
    chart.render_to_file(f'{language}_repos.svg')

languages = ['javascript', 'ruby', 'c', 'java', 'perl', 'haskell', 'go']
for language in languages:
    repos = get_top_repos(language)
    create_chart(repos, language)

import matplotlib.pyplot as plt
plt.savefig('17-1.png')
plt.show()
