# -*- coding: utf-8 -*-
"""17.2 TIY.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PZdZYjeiMX0J40wIgUIz4Pr4TaR56YHq
"""

import requests
import pygal
from pygal.style import LightColorizedStyle as LCS, LightenStyle as LS

def get_top_hn_submissions():
    """Get the top submissions on Hacker News."""
    url = "https://hacker-news.firebaseio.com/v0/topstories.json"
    response = requests.get(url)
    submission_ids = response.json()
    return submission_ids[:30]

def get_submission_details(submission_id):
    """Get details of a submission from Hacker News."""
    url = f"https://hacker-news.firebaseio.com/v0/item/{submission_id}.json"
    response = requests.get(url)
    submission_info = response.json()
    return submission_info

def create_chart(submissions):
    """Create a bar chart of the most active discussions on Hacker News."""
    names, comments, links = [], [], []
    for submission in submissions:
        try:
            submission_info = get_submission_details(submission)
            title = submission_info['title']
            num_comments = submission_info['descendants']
            discussion_link = f"https://news.ycombinator.com/item?id={submission}"
            names.append(title)
            comments.append(num_comments)
            links.append(discussion_link)
        except KeyError:
            continue

    my_style = LS('#333366', base_style=LCS)

    chart = pygal.Bar(style=my_style, x_label_rotation=45, show_legend=False)
    chart.title = 'Most Active Discussions on Hacker News'
    chart.x_labels = names

    for name, comment, link in zip(names, comments, links):
        chart.add(f'{name} ({comment})', [{'value': comment, 'xlink': {'href': link}}])

    chart.render_to_file('hn_discussions.svg')

if __name__ == '__main__':
    top_submissions = get_top_hn_submissions()
    create_chart(top_submissions)

import matplotlib.pyplot as plt
plt.savefig('17-2.png')
plt.show()
