# -*- coding: utf-8 -*-
"""Myowncode(weatherforcast).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XDa51ZACae40ZK9TyS6wAbHkLEROycpK
"""

import requests

def fetch_weather_forecast(api_key, city, country_code):
    """Fetch weather forecast data from OpenWeatherMap API."""
    url = f"http://api.openweathermap.org/data/2.5/forecast?q={city},{country_code}&appid={api_key}&units=metric"
    response = requests.get(url)
    weather_forecast = response.json()
    return weather_forecast

def display_weather_forecast(weather_forecast):
    """Display weather forecast data."""
    print("Weather Forecast:")
    for forecast in weather_forecast['list']:
        date_time = forecast['dt_txt']
        temperature = forecast['main']['temp']
        weather_description = forecast['weather'][0]['description']
        print(f"Date/Time: {date_time}, Temperature: {temperature}°C, Weather: {weather_description}")

if __name__ == '__main__':
    api_key = 'a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6'
    city = 'London'
    country_code = 'GB'

    weather_forecast = fetch_weather_forecast(api_key, city, country_code)
    display_weather_forecast(weather_forecast)
import matplotlib.pyplot as plt
plt.savefig('myowncode.png')
plt.show()
