# -*- coding: utf-8 -*-
"""15.1 TIY.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1heRV02LKwZONgjG1bVd-6UYmt4E6ISbP
"""

#15.1 TIY
import matplotlib.pyplot as plt

numbers = [1, 2, 3, 4, 5]
cubes = [num ** 3 for num in numbers]

plt.plot(numbers, cubes, marker='o')
plt.title('First Five Cubic Numbers')
plt.xlabel('Number')
plt.ylabel('Cube')
plt.grid(True)
plt.show()

numbers = list(range(1, 5001))
cubes = [num ** 3 for num in numbers]

plt.plot(numbers, cubes, marker='', linestyle='-')
plt.title('First 5,000 Cubic Numbers')
plt.xlabel('Number')
plt.ylabel('Cube')
plt.grid(True)
plt.show()