# -*- coding: utf-8 -*-
"""15.2 TIY.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NUZ248usQi0Zf3B6xVNhYTJwhuDhbeg2
"""

import matplotlib.pyplot as plt
import numpy as np

numbers = np.arange(1, 5001)
cubes = numbers ** 3

plt.scatter(numbers, cubes, c=cubes, cmap='viridis', marker='.', s=5)
plt.title('First 5,000 Cubic Numbers with Colormap')
plt.xlabel('Number')
plt.ylabel('Cube')
plt.colorbar(label='Cube')
plt.grid(True)
plt.show()