# -*- coding: utf-8 -*-
"""15.3TIY.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tpvzauvwGPjo7S1N_i-4i1T-EVnAqbsY
"""

import matplotlib.pyplot as plt
from random_walk import RandomWalk

rw = RandomWalk(5000)
rw.fill_walk()

plt.style.use('seaborn')
fig, ax = plt.subplots(figsize=(10, 6))

ax.plot(rw.x_values, rw.y_values, linewidth=1)

ax.scatter(0, 0, c='green', edgecolors='none', s=100)
ax.scatter(rw.x_values[-1], rw.y_values[-1], c='red', edgecolors='none', s=100)

ax.get_xaxis().set_visible(False)
ax.get_yaxis().set_visible(False)

plt.savefig('random_walk_plot.png')
plt.show()