# -*- coding: utf-8 -*-
"""15.5TIY.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gKXYdV1Dip_U8EsmVkQKFeHXfrN2y8TV
"""

from random import choice

class RandomWalk:
    """A class to generate random walks."""

    def __init__(self, num_points=5000):
        """Initialize attributes of a walk."""
        self.num_points = num_points

        self.x_values = [0]
        self.y_values = [0]

    def get_step(self):
        """Calculate the direction and distance for each step."""
        direction = choice([1, -1])
        distance = choice([0, 1, 2, 3, 4])
        return direction * distance

    def fill_walk(self):
        """Calculate all the points in the walk."""

        while len(self.x_values) < self.num_points:
            x_step = self.get_step()
            y_step = self.get_step()


            next_x = self.x_values[-1] + x_step
            next_y = self.y_values[-1] + y_step

            self.x_values.append(next_x)
            self.y_values.append(next_y)