# -*- coding: utf-8 -*-
"""15.6TIY.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OaV16nvnnEto5-7rHQcmIFPvIZ54J01O
"""

import random
import matplotlib.pyplot as plt

def roll_dice():
    """Simulate rolling two eight-sided dice."""
    return random.randint(1, 8) + random.randint(1, 8)

num_rolls = 1000
results = [roll_dice() for _ in range(num_rolls)]

plt.hist(results, bins=range(2, 17), edgecolor='black', align='left')
plt.title('Results of Rolling Two Eight-Sided Dice {} Times'.format(num_rolls))
plt.xlabel('Sum of Two Dice')
plt.ylabel('Frequency')
plt.grid(True)
plt.show()