# -*- coding: utf-8 -*-
"""15.7 TIY.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vvRmXOcdtx5wb7FTKOBK5DDJ_tl0UpwT
"""

import random
import matplotlib.pyplot as plt

def roll_three_d6():
    """Simulate rolling three six-sided dice (D6) and return the sum."""
    return sum(random.randint(1, 6) for _ in range(3))

num_rolls = 1000
results = [roll_three_d6() for _ in range(num_rolls)]

plt.hist(results, bins=range(3, 19), edgecolor='black', align='left')
plt.title('Results of Rolling Three D6 Dice {} Times'.format(num_rolls))
plt.xlabel('Sum of Three D6 Dice')
plt.ylabel('Frequency')
plt.grid(True)
plt.show()