# -*- coding: utf-8 -*-
"""15.8TIY.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HXQOQWJSJ0XhjHz0hWyro6L6qtUC-712
"""

import random
import matplotlib.pyplot as plt

def roll_two_d6_multiply():
    """Simulate rolling two six-sided dice (D6) and multiply the results."""
    return random.randint(1, 6) * random.randint(1, 6)

num_rolls = 1000
results = [roll_two_d6_multiply() for _ in range(num_rolls)]

plt.hist(results, bins=range(1, 37), edgecolor='black', align='left')
plt.title('Results of Multiplying Two D6 Dice {} Times'.format(num_rolls))
plt.xlabel('Product of Two D6 Dice')
plt.ylabel('Frequency')
plt.grid(True)
plt.show()